name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    # Pull requestがrenovate[bot]によるものであれば、テストをスキップする
    if: github.actor != 'renovate[bot]'
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v7
      - name: 🤖 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🧪 Test validation
        run: npm test
